### ISSUE TITLE
哇建中誒！希望我也可以讀這個學校！（國二升國三）

### ISSUE THREAD

**Issue by olivertzeng** [XiaoPanPanKevinPan/JianGuoHighSchool_RSS#2]
我以後上建中的時候一定會試試看這個東西的，看起來很酷！

**Comment by XiaoPanPanKevinPan** [comment]
> 我以後上建中的時候一定會試試看這個東西的，看起來很酷！

你好電，我國中都還沒有一個 GitHub 帳號 :smiling_face_with_tear: 
然後我現在基本上也只會把 Github 當成雲端硬碟而已……你就已經開了兩個 pull requests 還被 merged 了

我已經確信你會考上建中了。我非常建議你高一努力玩社團，然後高二當幹部。建中有資訊&電研，我推薦資訊社因為我是ww；而我不是幹部，所以我現在後悔莫及，我們班（第三班群）每一個資訊社的幾乎都是幹部，我被電爛……

加油！

**Comment by olivertzeng** [comment]
謝謝學長🙏！

**Comment by olivertzeng** [comment]
closing issue bruh
